FROM python:3.9.2-alpine

RUN apk update
RUN apk add g++ clang bash make && rm -rf /var/cache/apk/*

# Work directory
WORKDIR /home/dis-cover/dis-cover

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN ln -s /home/dis-cover/dis-cover/dis-cover/__main__.py /bin/dis-cover
